module.exports = [
    { id: 1, 
        company_name: 'BlueSky Builders', 
        email: 'estimating@blueskybuilders.com', 
        password: 'password123' },
      { id: 2, 
        company_name: 'Solid Foundations Construction', 
        email: 'estimating@solidfoundations.com', 
        password: 'construction456' },
      { id: 3, 
        company_name: 'Ace Construction Solutions', 
        email: 'estimating@aceconstructionsolutions.com', 
        password: 'securepass' },
      { id: 4, 
        company_name: 'GreenLeaf Contractors', 
        email: 'estimating@greenleafcontractors.com', 
        password: 'contractor2023' },
      { id: 5, 
        company_name: 'Superior Builders Inc.', 
        email: 'estimating@superiorbuilders.com', 
        password: 'buildmaster' }
]